version: "3"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx-proxy-letsencrypt

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=reverse-proxy
      - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory

  nodejs:
    image: nodejs
    container_name: nodejs
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DOCKER=true
      - ENV=production
      - VIRTUAL_HOST=bestfest.gordey.dev
      - LETSENCRYPT_HOST=bestfest.gordey.dev
      - VIRTUAL_PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: bestfest
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DEFAULT_ADMIN_USERNAME: ${MONGO_DEFAULT_ADMIN_USERNAME}
      MONGO_DEFAULT_ADMIN_PASSWORD: ${MONGO_DEFAULT_ADMIN_PASSWORD}
    volumes:
      - db:/data/db
      - dbconfig:/data/configdb
      - ./devops/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  db:
    driver: local
  dbconfig:
    driver: local
  certs:
  vhost.d:
  html:




